name: lcov Code Coverage Report
description: Comments a pull request with the code coverage
author: Justin Dietz
branding:
  icon: umbrella
  color: gray-dark
inputs:
  github-token:
    description: Github token
    required: true
    default: ${{ github.token }}
  lcov-file:
    description: The location of the lcov.info file
    required: false
  lcov-base:
    description: The location of the lcov file for the base branch
    required: false
  filter-changed-files:
    description: Set to true to only comment with coverage on files changed in this commit
    required: false
    default: false
  delete-old-comments:
    description: Set to true to delete old Coverage Report comments
    required: false
    default: false
  working-directory:
    description: Set working directory if project is not in root folder
    required: false
    default: "./"
  title:
    description: Title to add to the comment
    required: false
  omit-statement-percentage:
    description: Set to true to hide the statement percentage
    required: false
    default: false
  omit-branch-percentage:
    description: Set to true to hide the branch percentage
    required: false
    default: false
  omit-function-percentage:
    description: Set to true to hide the function percentage
    required: false
    default: false
  omit-line-percentage:
    description: Set to true to hide the line percentage
    required: false
    default: false
  omit-uncovered-lines:
    description: Set to true to hide the uncovered lines
    required: false
    default: false
runs:
  using: node16
  main: dist/main.js
